### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by cdhowie** [dobesv/node-binstruct#7]
I have a project on 0.2.0 of this module, but 0.3.1 has been released. As per semver, updates of 0.x.x modules are not guaranteed to be backwards compatible, so it would be helpful if there was a changelog so that I can see what changed and whether I need to make any changes in my code.

**Comment by dobesv** [comment]
Yeah, sounds good.  If you go through the commit history you can probably put one together and submit a PR for that.

**Comment by cdhowie** [comment]
I will try to do this in the next few weeks.
